### ISSUE TITLE
Set PAC proxy not working

### ISSUE THREAD

**Issue by cyfdecyf** [ohdarling/ProxyMenu#1]
I added some debug code and found that the address type is `null` on [PMAppDelegate.m#L166](https://github.com/ohdarling/ProxyMenu/blob/d4182e957b2d495fe3e195acaf0efa010e038b3b/ProxyMenu/PMAppDelegate.m) when proxy type is PAC. There's no problem setting HTTP or SOCKS proxy though.

I'm not able to fix the problem, so submit the issue to you.

**Comment by ohdarling** [comment]
Fixed it, check https://github.com/ohdarling/ProxyMenu/releases/tag/rel-v1.0.1

**Comment by cyfdecyf** [comment]
Working as expected, thanks.
